/** Textos de mascotas (M1, M2, M3, M10) en es-MX. Único lugar con copy de la feature. */
export const PETS_STRINGS = {
  list: {
    title: "Mis mascotas",
    empty: {
      title: "Aún no registras a tu mascota",
      body: "Con su perfil listo, un collar se activa en segundos y quien la encuentre sabrá a quién avisar.",
      action: "Registrar a mi mascota",
    },
    add: "Agregar mascota",
    limitReached: (max: number) => `Ya tienes el máximo de ${max} mascotas por cuenta.`,
    role: { DUENO: "Dueño", GUARDIAN: "Guardián" },
    collar: {
      none: "Sin collar",
      ACTIVO: "Collar activo",
      LISTO: "Collar listo",
      EN_REVISION: "Collar en revisión",
      REVOCADO: "Collar revocado",
      FABRICADO: "Collar sin preparar",
      muted: "Collar en silencio",
    },
    scanCollar: "Escanear un collar",
    signInPrompt: "Entra con tu cuenta para ver y registrar a tus mascotas.",
  },
  status: {
    EN_CASA: "En casa",
    PERDIDA: "Se busca",
    INACTIVA: "Inactiva",
  },
  species: { PERRO: "Perro", GATO: "Gato", OTRO: "Otro" },
  speciesEmoji: { PERRO: "🐶", GATO: "🐱", OTRO: "🐰" },
  sex: { MACHO: "Macho", HEMBRA: "Hembra", DESCONOCIDO: "No sé" },
  profile: {
    lostSince: (days: number) => (days === 1 ? "1 día en búsqueda" : `${days} días en búsqueda`),
    sections: {
      about: "Sobre su perfil",
      collar: "Collar",
      visibility: "Qué ve quien la encuentre",
      guardians: "Guardianes",
      history: "Historial",
    },
    fields: {
      description: "Señas",
      birthDate: "Nacimiento",
      sterilized: "Esterilización",
      microchip: "Microchip",
      medicalNotes: "Notas médicas",
      publicCode: "Código del QR",
    },
    sterilized: { yes: "Sí", no: "No", unknown: "Sin dato" },
    empty: "Sin dato",
    actions: {
      edit: "Editar perfil",
      markLost: "Se perdió",
      markFound: "¡Ya volvió a casa!",
      viewCase: "Ver su caso",
      activateCollar: "Activar collar",
      collarDetails: "Historial y silencio del collar",
      guardians: "Guardianes e invitaciones",
      publicPreview: "Ver lo que ve quien la encuentre",
      changes: "Cambios del perfil",
      deactivate: "Dar de baja",
    },
    visibility: {
      phone: { on: "Tu teléfono se muestra al escanear el collar", off: "Tu teléfono no se muestra; te avisan por la app" },
      notes: { on: "Las notas médicas se muestran", off: "Las notas médicas están ocultas" },
    },
    collarStatus: {
      active: (since: string) => `Activo desde ${since}`,
      muted: (remaining: string) => `En silencio · ${remaining}`,
      none: "Esta mascota no tiene collar vinculado. Actívalo acercando el teléfono al collar.",
      inReview: "El collar está en revisión: no envía avisos hasta que administración lo resuelva.",
    },
    foundConfirm: {
      title: "¿Ya volvió a casa?",
      body: "Cerraremos su caso y avisaremos a la comunidad con buenas noticias.",
      confirm: "Sí, ya está en casa",
      cancel: "Todavía no",
    },
    deactivateConfirm: {
      title: "Dar de baja el perfil",
      body: "La mascota pasa a inactiva: su collar se desvincula y su perfil deja de mostrarse. Puedes registrarla de nuevo más adelante.",
      confirm: "Dar de baja",
      cancel: "Cancelar",
    },
    changes: {
      title: "Cambios del perfil",
      empty: "Sin cambios registrados.",
      fields: {
        NOMBRE: "Nombre",
        ESPECIE: "Especie",
        SEXO: "Sexo",
        DESCRIPCION: "Señas",
        FECHA_NACIMIENTO: "Nacimiento",
        ESTERILIZADO: "Esterilización",
        MICROCHIP: "Microchip",
        NOTAS_MEDICAS: "Notas médicas",
        TELEFONO_VISIBLE: "Teléfono visible",
        NOTAS_VISIBLES: "Notas visibles",
        FOTOS: "Fotos",
      },
      by: (name: string) => `por ${name}`,
      system: "por el sistema",
      arrow: "→",
      blank: "vacío",
    },
    previewTitle: "Así te ve quien la encuentre",
    previewHint: "Nombre y foto siempre; teléfono y notas solo si los activaste.",
    guardianOnly: "Solo el dueño puede editar el perfil, transferir o desvincular el collar.",
    notFound: "Esta mascota ya no está disponible.",
  },
  form: {
    createTitle: "Nueva mascota",
    editTitle: "Editar perfil",
    photos: {
      label: "Fotos",
      hint: (max: number) => `Hasta ${max}. La primera es la portada.`,
      add: "Agregar foto",
      fromLibrary: "Elegir de la galería",
      takePhoto: "Tomar foto",
      remove: "Quitar foto",
      cover: "Portada",
      makeCover: "Hacer portada",
      denied: "Sin permiso para las fotos. Actívalo en Ajustes del sistema.",
      required: "Agrega al menos una foto.",
      processing: "Preparando fotos…",
    },
    name: { label: "Nombre", placeholder: "Ej. Toby" },
    species: { label: "Especie" },
    speciesDetail: { label: "¿Qué animal es?", placeholder: "Ej. Conejo, tortuga…" },
    sex: { label: "Sexo" },
    description: {
      label: "Señas",
      placeholder: "Color, tamaño, marcas, comportamiento. Lo que ayude a reconocerla.",
    },
    birthDate: { label: "Fecha aproximada de nacimiento", placeholder: "Sin fecha", clear: "Quitar", confirm: "Listo" },
    sterilized: { label: "¿Está esterilizada?", options: { yes: "Sí", no: "No", unknown: "No sé" } },
    microchip: {
      label: "Microchip",
      placeholder: "Número del chip, si tiene",
      hint: "Una vez guardado no se puede cambiar desde la app.",
      locked: "El microchip ya quedó registrado; para corregirlo escríbenos.",
    },
    medicalNotes: {
      label: "Notas médicas",
      placeholder: "Medicamentos, alergias, cuidados. Solo se muestran si lo activas abajo.",
    },
    visibility: {
      title: "Qué ve quien la encuentre",
      phone: {
        title: "Mostrar mi teléfono",
        description: "Solo en lecturas verificadas del collar. Si está apagado, te avisan por la app.",
      },
      notes: {
        title: "Mostrar notas médicas",
        description: "Útil si necesita medicamento; visible para cualquiera que escanee el collar.",
      },
    },
    submitCreate: "Guardar mascota",
    submitEdit: "Guardar cambios",
    saved: "Perfil guardado.",
    errors: {
      nameMin: (min: number) => `El nombre necesita al menos ${min} letras`,
      nameMax: (max: number) => `Máximo ${max} caracteres`,
      speciesDetailRequired: "Di qué animal es",
      speciesDetailMax: (max: number) => `Máximo ${max} caracteres`,
      descriptionMin: (min: number) => `Cuenta un poco más: al menos ${min} caracteres`,
      descriptionMax: (max: number) => `Máximo ${max} caracteres`,
      microchipFormat: "Solo letras y números, sin espacios",
      microchipMax: (max: number) => `Máximo ${max} caracteres`,
      medicalNotesMax: (max: number) => `Máximo ${max} caracteres`,
      birthDate: "La fecha no es válida",
    },
  },
  lostMode: {
    title: "Avisar que se perdió",
    notice: {
      title: "Antes de publicar 🐾",
      p1: (appName: string) => `${appName} existe para ayudarte a encontrar a tu mascota.`,
      p2a: "Comparte solo la ",
      p2strong: "información de tu mascota y un número de contacto",
      p2b: ". Evita dar datos personales: puede haber personas malintencionadas.",
      p3a: "Si concretas una reunión, ",
      p3strong: "que siempre sea en un lugar público",
      p3b: ".",
      accept: "Estoy de acuerdo",
    },
    form: {
      intro: (name: string) =>
        `Crearemos un caso con las fotos y señas de ${name}. Solo falta dónde y cómo contactarte.`,
      cp: { label: "Código postal de la zona", placeholder: "5 dígitos" },
      colonia: { label: "Colonia", placeholder: "Elige la colonia", searching: "Buscando colonias…" },
      cpNotFound: "No encontramos ese código postal.",
      cpInactive: (municipio: string, estado: string) =>
        `Por ahora no operamos en ${municipio} (${estado}). Si crees que es un error, escríbenos.`,
      locationReference: {
        label: "Referencia del lugar",
        placeholder: "Ej. Cerca del parque, por la tienda de la esquina",
      },
      point: {
        label: "Punto aproximado en el mapa",
        hint: "Arrastra el pin al último lugar donde la viste. Nadie verá tu casa: puedes soltarlo en una esquina.",
        useMyLocation: "Usar mi ubicación",
        locating: "Leyendo ubicación…",
        denied: "Sin permiso de ubicación. Mueve el pin a mano.",
        required: "Marca el punto en el mapa.",
      },
      phone: { label: "Teléfono de contacto", placeholder: "10 dígitos", hint: "Se muestra en el caso con relevo: nadie lo ve sin tocar «Ver teléfono»." },
      reward: { title: "Ofrezco recompensa", description: "Solo se indica que hay recompensa; nunca el monto." },
      continue: "Continuar",
      errors: {
        colonia: "Elige la colonia",
        referenceMin: (min: number) => `Al menos ${min} caracteres`,
        referenceMax: (max: number) => `Máximo ${max} caracteres`,
        phone: (length: number) => `Escribe ${length} dígitos`,
        point: "Marca el punto en el mapa",
      },
    },
    responsiva: {
      title: "Una última cosa",
      p1a: (appName: string) => `${appName} es una plataforma `,
      p1strong: "comunitaria y gratuita",
      p1b: ": su único objetivo es ayudar a los ciudadanos a reencontrarse con sus mascotas.",
      p2a: "Al publicar aceptas que la plataforma ",
      p2strong: "no se hace responsable",
      p2b: " del contacto entre personas. Sé cauteloso con quienes se comuniquen contigo.",
      accept: "Acepto, publicar",
      back: "Revisar de nuevo",
      submitting: "Publicando…",
    },
    done: {
      title: "Su caso ya está publicado",
      body: "La comunidad y quien escanee su collar ya saben que la buscas. Te avisaremos de cada novedad.",
      viewCase: "Ver el caso",
      close: "Cerrar",
    },
  },
} as const;
